<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.5" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.26" />
    <PackageReference Include="MimeKit" Version="4.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PocketCartApp.Repository\PocketCartApp.Repository.csproj" />
  </ItemGroup>

</Project>
